import Link from "next/link";
import Layout from "../components/Layout";

export default function About() {
  return (
    <Layout>
      <h1>About</h1>
      <p>
        Click the link below to navigate to a page generated by <code>next-mdx-remote</code>.
      </p>
      <ul></ul>
    </Layout>
  );
}
